<?php

/**
 * Implements hook_entity_info().
 */
 
DEFINE('MODULE_PATH',drupal_get_path('module', 'publication'));

drupal_add_css(MODULE_PATH. '/publication.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));

function publication_entity_info() {
  $return = array(
    'publication' => array(
      'label' => t('Publication'),
      'entity class' => 'Publication',
      'controller class' => 'PublicationController',
      'base table' => 'publication',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'pub_id',
        'bundle' => 'type',
		  'uuid' => 'uuid',
      	),
      'bundle keys' => array(
        'bundle' => 'type',
      	),
      'bundles' => array(),
      'load hook' => 'publication_load',
      'uuid' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Full'),
          'custom settings' => FALSE,
        	),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => FALSE,
        	),
        'title_only' => array(
          'label' => t('Title only'),
          'custom settings' => FALSE,
        	),
        'title_cover' => array(
          'label' => t('Title + Cover'),
          'custom settings' => FALSE,
        	),
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'publication',
      'access callback' => 'publication_access',
    ),
  );
  $return['publication_type'] = array(
    'label' => t('Publication type'),
    'entity class' => 'PublicationType',
    'controller class' => 'PublicationTypeController',
    'base table' => 'publication_type',
    'fieldable' => FALSE,
    'bundle of' => 'publication',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'publication',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/publication-types',
      'file' => 'publication.admin.inc',
      'controller class' => 'PublicationTypeUIController',
    ),
    'access callback' => 'publication_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function publication_entity_info_alter(&$entity_info) {
  foreach (publication_types() as $type => $info) {
    $entity_info['publication']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/publication-types/manage/%publication_type',
        'real path' => 'admin/structure/Publication-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function publication_menu() {
  $items = array();
  
  $items['publications'] = array(
	 'title' => t('Publications'),
	 'page callback' => 'get_subjects',
	 //'page arguments' => array('user'),
	 'access arguments' => array('view publication entities'),
	 'menu_name' => 'main-menu',
	 'weight' => -40,
	 'type' => MENU_NORMAL_ITEM,

	);
	
	$items['publications/%/%'] = array(
	  'title callback' => 'get_subject_title',
	  'title arguments'=> array(1,2),
	  'page callback'  => 'subject_page',
	  'page arguments' => array(1,2),	
	  'access arguments'=> TRUE,

	);
		
  $items['publication/add'] = array(
    'title' => 'Add publication',
    'page callback' => 'publication_admin_add_page',
    'access arguments' => array('administer publication entities'),
    'file' => 'publication.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'tab_parent' => 'publication',
    'tab_root' => 'publication',
  );

  $publication_uri = 'publication/%publication';
  $publication_uri_argument_position = 1;

  $items[$publication_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('publication', $publication_uri_argument_position),
    'page callback' => 'publication_view',
    'page arguments' => array($publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'publication', $publication_uri_argument_position),
    'file' => 'publication.pages.inc',
  );

  $items[$publication_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$publication_uri . '/delete'] = array(
    'title' => 'Delete publication',
    'title callback' => 'publication_label',
    'title arguments' => array($publication_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_delete_form', $publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'publication', $publication_uri_argument_position),
    'file' => 'publication.admin.inc',
  );

  $items[$publication_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_form', $publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'publication', $publication_uri_argument_position),
    'file' => 'publication.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  foreach (publication_types() as $type => $info) {
    $items['publication/add/' . $type] = array(
      'title' => 'Add publication',
      'page callback' => 'publication_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'publication', $type),
      'file' => 'publication.admin.inc',
    );
  }

  $items['admin/structure/publication-types/%publication_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_type_form_delete_confirm', 4),
    'access arguments' => array('administer publication types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'publication.admin.inc',
  );
  
  return $items;
}

function publication_menu_alter(&$items) {
  if (!empty($items['taxonomy/term/%taxonomy_term'])) {
    $items['taxonomy/term/%taxonomy_term']['page callback'] = 'publication_term_page';
  }
}


/**
 * Implements hook_permission().
 */
function publication_permission() {
  $permissions = array(
    'administer publication types' => array(
      'title' => t('Administer publication types'),
      'description' => t('Allows users to configure publication types and their fields.'),
      'restrict access' => TRUE,
    ),
    'administer publication entities' => array(
      'title' => t('Administer publication entities'),
      'description' => t('Allows users to administer publication entities.'),
      'restrict access' => TRUE,
    ),
    'create publication entities' => array(
      'title' => t('Create publications'),
      'description' => t('Allows users to create publications.'),
      'restrict access' => FALSE,
    ),
    'view publication entities' => array(
      'title' => t('View publications'),
      'description' => t('Allows users to view publications.'),
      'restrict access' => FALSE,
    ),
    'edit any publication entities' => array(
      'title' => t('Edit any publications'),
      'description' => t('Allows users to edit any publications.'),
      'restrict access' => TRUE,
    ),
    'edit own publication entities' => array(
      'title' => t('Edit own publications'),
      'description' => t('Allows users to edit own publications.'),
      'restrict access' => FALSE,
    ),
  );

  return $permissions;
}


/**
 * Implements hook_entity_property_info_alter().
 */
function publication_entity_property_info_alter(&$info) {
  $properties = &$info['publication']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the publication was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'create publication entities',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the node was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the Publication."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer publication entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}

/*
 * Implements hook_field_extra_fields()
 */
function publication_field_extra_fields(){
	$extra = array();
	foreach (publication_types() as $type => $info) {
		$extra['publication'][$type] = array(
			'form' => array(
      		'title' => array(
        			'label' => t('Title'),
        			'description' => t('Publication module element'),
        			'weight' => -4,
      		),
      	 ),
      	'display' => array(
      		'title' => array(
        			'label' => t('Title'),
        			'description' => t('Publication module element'),
        			'weight' => -4,
      	 	),
			),
		);
  	}
  	return $extra;
}

/*
 * Implements hook_entity_view().
 */

function publication_entity_view($entity, $type, $view_mode, $langcode) {
 /*
 // Extra fields for publications
  if ($type == 'publication' ) {
    $extra_fields = field_extra_fields_get_display('publication', $entity->type, $view_mode);
    // Get extrafield visibility.
    if (!empty($extra_fields['title']) && $extra_fields['title']['visible'] == TRUE) {
      // Do something awesome depending on the $view_mode (I've just added a default for all view_modes)
      switch ($view_mode) {
        default:
          $entity->content['title'] = array(
            '#markup' => $entity->title
          	);
      }
    }
  }
  unset($entity->content['author']);
  */
}

/*******************************************************************************
 ********************************* Publication API's **********************************
 ******************************************************************************/

/**
 * Access callback for Publication.
 */
function publication_access($op, $publication = NULL, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
  	 case 'administrer':
      return user_access('administer publication entities', $account);
    case 'create':
      return user_access('administer publication entities', $account)
          || user_access('create publication entities', $account);
    case 'view':
      return user_access('administer publication entities', $account)
          || user_access('view publication entities', $account);
    case 'edit':
      return user_access('administer publication entities')
          || user_access('edit any publication entities')
          || (user_access('edit own publication entities') && ($publication->uid == $account->uid));
  }
}

/**
 * Load a Publication.
 */
function publication_load($pub_id, $reset = FALSE) {
  $publications = publication_load_multiple(array($pub_id), array(), $reset);
  return reset($publications);
}

/**
 * Load multiple Publications based on certain conditions.
 */
function publication_load_multiple($pub_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('publication', $pub_ids, $conditions, $reset);
}

/**
 * Save Publication.
 */
function publication_save($publication) {
  entity_save('publication', $publication);
}

/**
 * Delete single Publication.
 */
function publication_delete($publication) {
  entity_delete('publication', entity_id('publication' ,$publication));
}

/**
 * Delete multiple Publications.
 */
function publication_delete_multiple($publication_ids) {
  entity_delete_multiple('publication', $publication_ids);
}

/*******************************************************************************
 ****************************** Publication Type API's ********************************
 ******************************************************************************/

/**
 * Access callback for Publication Type.
 */
function publication_type_access($op, $entity = NULL) {
  return user_access('administer publication types');
}

/**
 * Load Publication Type.
 */
function publication_type_load($publication_type) {
  return publication_types($publication_type);
}

/**
 * List of Publication Types.
 */
function publication_types($type_name = NULL) {
  $types = entity_load_multiple_by_name('publication_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}

/**
 * Save Publication type entity.
 */
function publication_type_save($publication_type) {
  entity_save('publication_type', $publication_type);
}

/**
 * Delete single case type.
 */
function publication_type_delete($publication_type) {
  entity_delete('publication_type', entity_id('publication_type' ,$publication_type));
}

/**
 * Delete multiple case types.
 */
function publication_type_delete_multiple($publication_type_ids) {
  entity_delete_multiple('publication_type', $publication_type_ids);
}

/**
  * Implements hook_views_api().
  */
function publication_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'publication'),
  );
}


/*
 * Get all Subjects/Areas as a renderable array
 */
function get_subjects(){
	$voc = taxonomy_vocabulary_machine_name_load('subjects');	
	$subjects = taxonomy_get_tree($voc->vid);
	
	$terms = array();
	
	foreach($subjects as $subject){
		if($subject->depth == 0){
			$terms[$subject->tid] = array('name' => $subject->name,'children' => array());
		}else{
			$terms[$subject->parents[0]]['children'][$subject->tid] = $subject->name; 		
		}
	} 

	$render = array();
	
	foreach($terms as $key => $value){
		$render[$key] = array(
								'#prefix' => "<div class='subject-parent-box';'>",
								'#suffix' => "</div>",
								'markup' => array(
											  '#theme' => 'link',
											  '#text' => $value['name'],
											  '#path' => drupal_get_path_alias('taxonomy/term/' . $key),
											  '#options' => array(
											  							 'attributes' => array('title' => $value['name'],),
											  							 'html' => TRUE
											  							),
											  
											)
					 		);		
		if(count($value['children'])){		
			foreach($value['children'] as $k => $v){
				$render[$key]['children'][] = array(
													 '#theme' => 'link',
												    '#text' => $v,
												    '#path' => drupal_get_path_alias('taxonomy/term/' . $k),
												    '#options' => array(
												    						'attributes' => array('title' => $v),
												    						'html' => TRUE
												    					),
												    '#prefix' => "<div class='subject-child-box'>",
												    '#suffix' => "</div>",
												  );		
			}	
		}
	}
	
	return $render;
}


/*
 * Callback for publication term 
 */  
function publication_term_page($term){
	if($term->vocabulary_machine_name == 'subjects'){
		$content = array(
								'description' => array(
										'#markup' => $term->description,
										'#prefix' => "<div class='subject-description'>",
										'#suffix'=> '</div>',
								),				
					);
							
		$children_terms = taxonomy_get_children($term->tid);
		if(count($children_terms)){
			foreach($children_terms as $child_term){
				$children[] = array(
										'title' => array(
															'#theme' => 'link',
															'#text'  => $child_term->name,
															'#path'  => drupal_get_path_alias('taxonomy/term/' . $child_term->tid),
															'#options'=> array('attributes' => array('title' => ''),'html'=>TRUE),
															'#prefix'=> '<h3>',
															'#suffix'=> '</h3>',
															),
										'description' => array(
															'#markup' => $child_term->description,
															'#prefix'=> '',
															'#suffix'=> '</br>',
															),					
										);	
				}
			$content['children'] = $children;
		}else{
			$content['reports'] = array(
											'title' => array('#markup' => t('Reports'),'#prefix' => '<h2><b>','#suffix' => '</b></h2>'),
											'items' => array('#markup' => views_embed_view('publications','latest_reports_minimal',$term->tid)),
											'more'  => array('#theme' => 'link','#text' => t('More >>'),'#path' => 'publications/' . $term->name . '/reports','#options' => array('attributes' => array(),'html' => TRUE)),
												);
			$content['articles'] = array(
											'title' => array('#markup' => t('Articles'),'#prefix' => '<h2><b>','#suffix' => '</b></h2>'),
											'items' => array('#markup' => views_embed_view('publications','latest_articles_minimal',$term->tid)),
											'more'  => array('#theme' => 'link','#text' => t('More >>'),'#path' => 'publications/' . $term->name . '/articles','#options' => array('attributes' => array(),'html' => TRUE)),		
												);
		}	
		
		return $content;
	}
	return taxonomy_term_page($term);
}

