<?php

/**
 * Implements hook_entity_info().
 */
function nisr_application_entity_info() {
  $return = array(
    'nisr_application' => array(
      'label' => t('NISR Application'),
      'entity class' => 'NisrApplication',
      'controller class' => 'NisrApplicationController',
      'base table' => 'nisr_application',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'aid',
        'bundle' => 'type',
		  'uuid' => 'uuid',
      	),
      'bundle keys' => array(
        'bundle' => 'type',
      	),
      'bundles' => array(),
      'load hook' => 'nisr_application_load',
      'uuid' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Full'),
          'custom settings' => FALSE,
        	),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => FALSE,
        	),
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'nisr_application',
      'access callback' => 'nisr_application_access',
    ),
  );
  $return['nisr_application_type'] = array(
    'label' => t('Application type'),
    'entity class' => 'NisrApplicationType',
    'controller class' => 'NisrApplicationTypeController',
    'base table' => 'nisr_application_type',
    'fieldable' => FALSE,
    'bundle of' => 'nisr_application',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'nisr_application',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/nisr_application-types',
      'file' => 'nisr_application.admin.inc',
      'controller class' => 'NisrApplicationTypeUIController',
    ),
    'access callback' => 'nisr_application_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function nisr_application_entity_info_alter(&$entity_info) {
  foreach (nisr_application_types() as $type => $info) {
    $entity_info['nisr_application']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/nisr_application-types/manage/%nisr_application_type',
        'real path' => 'admin/structure/nisr_application-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function nisr_application_menu() {
  $items = array();

  $items['nisr_application/add'] = array(
    'title' => 'Add NISR application',
    'page callback' => 'nisr_application_admin_add_page',
    'access arguments' => array('create nisr_application entities'),
    'file' => 'nisr_application.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'tab_parent' => 'nisr_application',
    'tab_root' => 'nisr_application',
  );

  $nisr_application_uri = 'nisr_application/%nisr_application';
  $nisr_application_uri_argument_position = 1;

  $items[$nisr_application_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('nisr_application', $nisr_application_uri_argument_position),
    'page callback' => 'nisr_application_view',
    'page arguments' => array($nisr_application_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'nisr_application', $nisr_application_uri_argument_position),
    'file' => 'nisr_application.pages.inc',
  );

  $items[$nisr_application_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$nisr_application_uri . '/delete'] = array(
    'title' => 'Delete nisr_application',
    'title callback' => 'nisr_application_label',
    'title arguments' => array($nisr_application_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nisr_application_delete_form', $nisr_application_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'nisr_application', $nisr_application_uri_argument_position),
    'file' => 'nisr_application.admin.inc',
  );

  $items[$nisr_application_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nisr_application_form', $nisr_application_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'nisr_application', $nisr_application_uri_argument_position),
    'file' => 'nisr_application.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  foreach (nisr_application_types() as $type => $info) {
    $items['nisr_application/add/' . $type] = array(
      'title' => 'Add NISR application',
      'page callback' => 'nisr_application_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'nisr_application', $type),
      'file' => 'nisr_application.admin.inc',
    );
  }

  $items['admin/structure/nisr_application-types/%nisr_application_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nisr_application_type_form_delete_confirm', 4),
    'access arguments' => array('administer nisr_application types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nisr_application.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function nisr_application_permission() {
  $permissions = array(
    'administer nisr_application types' => array(
      'title' => t('Administer NISR application types'),
      'description' => t('Allows users to configure NISR application types and their fields.'),
      'restrict access' => TRUE,
    ),
    'administer nisr_application entities' => array(
      'title' => t('Administer NISR application entities'),
      'description' => t('Allows users to administer NISR application entities.'),
      'restrict access' => TRUE,
    ),
    'create nisr_application entities' => array(
      'title' => t('Create NISR applications'),
      'description' => t('Allows users to create NISR applications.'),
      'restrict access' => FALSE,
    ),
    'view any nisr_application entities' => array(
      'title' => t('View any NISR applications'),
      'description' => t('Allows users to view NISR applications.'),
      'restrict access' => TRUE,
    ),
    'view own nisr_application entities' => array(
      'title' => t('View own NISR applications'),
      'description' => t('Allows users to view own NISR applications.'),
      'restrict access' => FALSE,
    ),
    'edit any nisr_application entities' => array(
      'title' => t('Edit any NISR applications'),
      'description' => t('Allows users to edit any NISR applications.'),
      'restrict access' => TRUE,
    ),
    'edit own nisr_application entities' => array(
      'title' => t('Edit own NISR applications'),
      'description' => t('Allows users to edit own NISR applications.'),
      'restrict access' => FALSE,
    ),
  );

  return $permissions;
}


/**
 * Implements hook_entity_property_info_alter().
 */
function nisr_application_entity_property_info_alter(&$info) {
  $properties = &$info['nisr_application']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the NISR application was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'create nisr_application entities',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the NISR application was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the NISR application."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer nisr_application entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}

/*
 * Implements hook_field_extra_fields()
 */
function nisr_application_field_extra_fields(){
	$extra = array();
	foreach (nisr_application_types() as $type => $info) {
		$extra['nisr_application'][$type] = array(
			'form' => array(
      		'title' => array(
        			'label' => t('Title'),
        			'description' => t('Application module element'),
        			'weight' => -4,
      		),
      	 ),
		);
  	}
  	return $extra;
}

/*
 * Implements hook_entity_view().
 */

function nisr_application_entity_view($entity, $type, $view_mode, $langcode){
  //unset($entity->content['author']);
}


/*
 * Implements hook_nisr_application_insert()
 */
 
function nisr_application_nisr_application_insert(Application $nisr_application){
	if(!is_dir('public://applications/' . $nisr_application->uuid)){;
		drupal_mkdir('public://applications/' . $nisr_application->uuid);
	}
}


/*******************************************************************************
 ********************************* nisr_application API's **********************************
 ******************************************************************************/

/**
 * Access callback for nisr_application.
 */
function nisr_application_access($op, $nisr_application = NULL, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
  	 case 'administrer':
      return user_access('administer nisr_application entities', $account);
    case 'create':
      return user_access('administer nisr_application entities', $account)
          || user_access('create nisr_application entities', $account);
    case 'view':
      return user_access('administer nisr_application entities', $account)
          || user_access('view any nisr_application entities',$account)
          || user_access('view own nisr_application entities', $account);
    case 'edit':
      return user_access('administer nisr_application entities',$account)
          || user_access('edit any nisr_application entities',$account)
          || (user_access('edit own nisr_application entities') && ($nisr_application->uid == $account->uid));
  }
}

/**
 * Load a nisr_application.
 */
function nisr_application_load($aid, $reset = FALSE) {
  $nisr_applications = nisr_application_load_multiple(array($aid), array(), $reset);
  return reset($nisr_applications);
}

/**
 * Load multiple nisr_applications based on certain conditions.
 */
function nisr_application_load_multiple($aids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('nisr_application', $aids, $conditions, $reset);
}

/**
 * Save nisr_application.
 */
function nisr_application_save($nisr_application) {
  entity_save('nisr_application', $nisr_application);
}

/**
 * Delete single nisr_application.
 */
function nisr_application_delete($nisr_application) {
  entity_delete('nisr_application', entity_id('nisr_application' ,$nisr_application));
}

/**
 * Delete multiple nisr_applications.
 */
function nisr_application_delete_multiple($nisr_application_ids) {
  entity_delete_multiple('nisr_application', $nisr_application_ids);
}

/*******************************************************************************
 ****************************** nisr_application Type API's ********************************
 ******************************************************************************/

/**
 * Access callback for nisr_application Type.
 */
function nisr_application_type_access($op, $entity = NULL) {
  return user_access('administer nisr_application types');
}

/**
 * Load nisr_application Type.
 */
function nisr_application_type_load($nisr_application_type) {
  return nisr_application_types($nisr_application_type);
}

/**
 * List of nisr_application Types.
 */
function nisr_application_types($type_name = NULL) {
  $types = entity_load_multiple_by_name('nisr_application_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}

/**
 * Save nisr_application type entity.
 */
function nisr_application_type_save($nisr_application_type) {
  entity_save('nisr_application_type', $nisr_application_type);
}

/**
 * Delete single case type.
 */
function nisr_application_type_delete($nisr_application_type) {
  entity_delete('nisr_application_type', entity_id('nisr_application_type' ,$nisr_application_type));
}

/**
 * Delete multiple case types.
 */
function nisr_application_type_delete_multiple($nisr_application_type_ids) {
  entity_delete_multiple('nisr_application_type', $nisr_application_type_ids);
}

/**
  * Implements hook_views_api().
  */
function nisr_application_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'nisr_application'),
  );
}
