<?php

DEFINE('PUB_MODULE_PATH',drupal_get_path('module', 'publication'));

drupal_add_css(PUB_MODULE_PATH. '/publication.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));

/*
 * Implements hook_block_info()
 */
function publication_block_info(){
	$weight = 100;
	// Featured publications on homepage
	$blocks['featured_statistical_reports'] = array(
		'info' => t('Featured statistical reports'),
		'weight' => $weight,
		'cache' => DRUPAL_CACHE_GLOBAL,
		);
	$blocks['featured_statistical_articles'] = array(
		'info' => t('Featured statistical articles'),
		'weight' => $weight,
		'cache' => DRUPAL_CACHE_GLOBAL,
		);
	// Subjects on statistical page
	$blocks['subjects'] = array(
		'info' => t('Subjects/Areas'),
		'weight' => $weight,
		'cache' => DRUPAL_CACHE_GLOBAL,
		);
		
	// Declare blocks from document subjects vocabulary
	$voc = taxonomy_vocabulary_machine_name_load('document_subjects');	
	$subjects = taxonomy_get_tree($voc->vid);
	
	foreach($subjects as $subject){
		$blocks[str_replace(' ','_',strtolower($subject->name))] =  array(
			'info' => t($subject->name) . ' documents',
			//'weight' => ++$weight, 
			'cache' => DRUPAL_CACHE_GLOBAL	
			);
	} 
	
	return $blocks;
}

/*
 * Implements hook_block_view()
 */
function publication_block_view($delta = ''){
	module_load_include('inc','nisr','utils');
	if($delta == 'featured_statistical_reports'){
		$block['title'] = t('Featured reports');
		$view = get_embed_view('featured_publications','statistical_reports',array('831+832+836+833'));
		$block['content'] = $view['result'];
	}	
	
	if($delta == 'featured_statistical_articles'){
		$block['title'] = t('Latest news');
		$view = get_embed_view('featured_publications','statistical_articles',array());
		$block['content'] = $view['result'];
	}
	
	if($delta == 'subjects'){
		$block['title'] = '';
		$block['content'] = get_taxonomy_terms('subjects');
	}
	
	// Feed the dynamically declared blocks from document subjects vocabulary with view embed display
	$voc = taxonomy_vocabulary_machine_name_load('document_subjects');	
	$subjects = taxonomy_get_tree($voc->vid);
	
	foreach($subjects as $subject){
		if($delta == str_replace(' ','_',strtolower($subject->name))){
			$view =  get_embed_view('publications_search','documents',array($subject->tid));			
			$block['title'] = '';
			$block['content'] = $view['result'];
		}
	} 	
		
	return $block;
}

/*
 * Implements hook_entities_by_term()
 */
function publication_entities_by_term_alter(&$entities,$tid){
	module_load_include('inc','nisr','utils');
	$reports  = get_embed_view('publications_search','latest_statistical_reports',array($tid));
	$articles = get_embed_view('publications_search','latest_statistical_articles',array($tid));
	
	if($reports['count']){
		$entities['reports'] = array(
									"title" => array("#markup" => t($reports['title']),"#prefix" => "<div class=''><div class=''><h4 class=''>","#suffix" => "</h4></div>"),
									'items' => array('#markup' => $reports['result'],'#prefix' => "<div class='clearfix'>",'#suffix' => '</div>'),
										);

		$entities['reports']['more'] = array('#theme' => 'link','#text' => t('Read more'),'#path' => 'publications/statistical_reports/' . $tid ,'#options' => array('attributes' => array('class' => array('btn','btn-sm','btn-primary')),'html' => TRUE),'#prefix' =>"<div style='margin:15px;'>",'#suffix' => '</div></div>');
	}	
			
	if($articles['count']){
		$entities['articles'] = array(
									'title' => array('#markup' => t($articles['title']),"#prefix" => "<div class=''><div class=''><h4 class=''>","#suffix" => "</h4></div>"),
									'items' => array('#markup' => $articles['result'],'#prefix' => "<div class='clearfix' style='margin-left:15px;'>",'#suffix' => '</div>'),  
										);

		$entities['articles']['more'] = array('#theme' => 'link','#text' => t('Read More'),'#path' => 'publications/statistical_articles/' . $tid,'#options' => array('attributes' => array('class' => array('btn','btn-sm','btn-primary')),'html' => TRUE),'#prefix' =>"<div style='margin:15px;'>",'#suffix' => '</div></div>');
	}
	
		
}
/*
 * Implements hook_entity_info()
 */
function publication_entity_info() {
  $return = array(
    'publication' => array(
      'label' => t('Publication'),
      'entity class' => 'Publication',
      'controller class' => 'PublicationController',
      'base table' => 'publication',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'pub_id',
        'bundle' => 'type',
		  'uuid' => 'uuid',
      	),
      'bundle keys' => array(
        'bundle' => 'type',
      	),
      'bundles' => array(),
      'load hook' => 'publication_load',
      'uuid' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Full'),
          'custom settings' => FALSE,
        	),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => FALSE,
        	),
        'featured' => array(
          'label' => t('Featured'),
          'custom settings' => FALSE,
        	),
        'title_only' => array(
          'label' => t('Title only'),
          'custom settings' => FALSE,
        	),
        'title_cover' => array(
          'label' => t('Title + Cover'),
          'custom settings' => FALSE,
        	),
        'table' => array(
          'label' => t('Table'),
          'custom settings' => FALSE,
        	),        	
        'chart' => array(
          'label' => t('Chart'),
          'custom settings' => FALSE,
        	),        
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'publication',
      'access callback' => 'publication_access',
    ),
  );
  $return['publication_type'] = array(
    'label' => t('Publication type'),
    'entity class' => 'PublicationType',
    'controller class' => 'PublicationTypeController',
    'base table' => 'publication_type',
    'fieldable' => FALSE,
    'bundle of' => 'publication',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'publication',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/publication-types',
      'file' => 'publication.admin.inc',
      'controller class' => 'PublicationTypeUIController',
    ),
    'access callback' => 'publication_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function publication_entity_info_alter(&$entity_info) {
  foreach (publication_types() as $type => $info) {
    $entity_info['publication']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/publication-types/manage/%publication_type',
        'real path' => 'admin/structure/Publication-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/*
 * Implements hook_entity_update()
 */
function publication_entity_update($entity,$type){
	if($type == 'publication'){
		$subjects  = array();
		$subscribers = views_get_view('subscribers');
		switch($entity->type) {
			case 'statistical_report':
			case 'statistical_article':		
				// Get subjects
				$subscribers->set_display('statistical_publications');
				$wr = entity_metadata_wrapper('publication',$entity);
				foreach($wr->field_pub_subject as $subject){
					$subjects[] = $subject->tid->value();
				}
								
				break;
			case 'document':
				
				break;
			case '':
				break;
			default:
				break;
		}
		
		$subscribers->set_arguments($subjects);						
		$subscribers->pre_execute();
		$subscribers->execute();
		
		foreach($subscribers->result as $subscriber){
			$recipients[] = $subscriber->profile_uid;
		}
		
		if(count($recipients)) watchdog('nisr','%d email alerts sent',array('%d' => count($recipients)));
	}
	elseif($type== 'node' && $entity->type == 'article') {
		
	}
}

/*
 * Implements hook_entity_view().
 */

function publication_entity_view($entity, $type, $view_mode, $langcode) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Home'),'<front>');
  if ($type == 'publication' && $entity->type == 'statistical_report' && $view_mode == 'full' && count($entity->field_pub_subject)){
 		$wrapper = entity_metadata_wrapper('publication',$entity);
 		$term_id = $wrapper->field_pub_subject[0]->tid->value();
 		$term_name = $wrapper->field_pub_subject[0]->name->value();
 		 		
		$parent_terms = taxonomy_get_parents_all($term_id);
		unset($parent_terms[0]); // Remove the first element including the term object 		
		
		// Set breadcrumb in the form
		// Home > Publications > Statistics > Subject > Reports > Title 


		$breadcrumb[] = l(t('Statistical publications'),'statistical_publications');
	   foreach(array_reverse($parent_terms) as $parent){
	   	$breadcrumb[] = l(t($parent->name),drupal_get_path_alias('taxonomy/term/' . $parent->tid));
	   } 
	   
		$breadcrumb[] = l(t($term_name),drupal_get_path_alias('taxonomy/term/' . $term_id));
		$breadcrumb[] = l(t('Statistical reports'),'statistical_publications/' . $term_id . '/reports');
  	} 
	
	$breadcrumb[] = drupal_get_title();
	
	drupal_set_breadcrumb($breadcrumb);		
}

/**
 * Implements hook_menu().
 */
function publication_menu() {
  $items = array();

  $items['admin/content/publications/add'] = array(
    'title' => 'Add publication',
    'page callback' => 'publication_admin_add_page',
    'access arguments' => array('administer publication entities'),
    'file' => 'publication.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  	  
  $publication_uri = 'publication/%publication';
  $publication_uri_argument_position = 1;

  $items[$publication_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('publication', $publication_uri_argument_position),
    'page callback' => 'publication_view',
    'page arguments' => array($publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'publication', $publication_uri_argument_position),
    'file' => 'publication.pages.inc',
  );

  $items[$publication_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$publication_uri . '/delete'] = array(
    'title' => 'Delete publication',
    'title callback' => 'publication_label',
    'title arguments' => array($publication_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_delete_form', $publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'publication', $publication_uri_argument_position),
    'file' => 'publication.admin.inc',
  );

  $items[$publication_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_form', $publication_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'publication', $publication_uri_argument_position),
    'file' => 'publication.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'theme callback' => 'variable_get',
    'theme arguments' => array('admin_theme'),
  );

  foreach (publication_types() as $type => $info) {
    $items['publication/add/' . $type] = array(
      'title' => 'Add publication',
      'page callback' => 'publication_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'publication', $type),
      'file' => 'publication.admin.inc',
      'theme callback' => 'variable_get',
      'theme arguments' => array('admin_theme'),
    );
  }

  $items['admin/structure/publication-types/%publication_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_type_form_delete_confirm', 4),
    'access arguments' => array('administer publication types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'publication.admin.inc',
  );
  
  return $items;
}

/*
function publication_menu_alter(&$items) {
  global $user;
	
  if (!empty($items['taxonomy/term/%taxonomy_term'])) {
		$items['taxonomy/term/%taxonomy_term']['page callback'] = 'subject_page';
	 	$items['taxonomy/term/%taxonomy_term']['access arguments'] = array('view publication entities');        
  }
}
*/

/**
 * Implements hook_permission().
 */
function publication_permission() {
  $permissions = array(
    'administer publication types' => array(
      'title' => t('Administer publication types'),
      'description' => t('Allows users to configure publication types and their fields.'),
      'restrict access' => TRUE,
    ),
    'administer publication entities' => array(
      'title' => t('Administer publication entities'),
      'description' => t('Allows users to administer publication entities.'),
      'restrict access' => TRUE,
    ),
    'create publication entities' => array(
      'title' => t('Create publications'),
      'description' => t('Allows users to create publications.'),
      'restrict access' => FALSE,
    ),
    'view publication entities' => array(
      'title' => t('View publications'),
      'description' => t('Allows users to view publications.'),
      'restrict access' => FALSE,
    ),
    'edit any publication entities' => array(
      'title' => t('Edit any publications'),
      'description' => t('Allows users to edit any publications.'),
      'restrict access' => TRUE,
    ),
    'edit own publication entities' => array(
      'title' => t('Edit own publications'),
      'description' => t('Allows users to edit own publications.'),
      'restrict access' => FALSE,
    ),
    'delete any publication entities' => array(
      'title' => t('Delete any publications'),
      'description' => t('Allows users to delete any publications.'),
      'restrict access' => TRUE,
    ),
    'delete own publication entities' => array(
      'title' => t('Delete own publications'),
      'description' => t('Allows users to delete own publications.'),
      'restrict access' => FALSE,
    ),
  );

  return $permissions;
}


/**
 * Implements hook_entity_property_info_alter().
 */
function publication_entity_property_info_alter(&$info) {
  $properties = &$info['publication']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the publication was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'create publication entities',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the node was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the Publication."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer publication entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}


/*
 * Implements hook_field_extra_fields()
 */
function publication_field_extra_fields(){
	$extra = array();
	foreach (publication_types() as $type => $info) {
		$extra['publication'][$type] = array(
			'form' => array(
      		'title' => array(
        			'label' => t('Title'),
        			'description' => t('Publication module element'),
        			'weight' => -4,
      		),
      	 ),
      	'display' => array(
      		'title' => array(
        			'label' => t('Title'),
        			'description' => t('Publication module element'),
        			'weight' => -4,
      	 	),
			),
		);
  	}
  	return $extra;
}

/*
 * Implements hook_form_FORM_ID_alter()
 */
function publication_form_publication_form_alter(&$form,&$form_state,$form_id){
	// Hide the elapsed periods field which is populated automatically during indexing
	$form['field_pub_elapsed_periods']['#prefix'] = "<div style='visibility:hidden'>";
	$form['field_pub_elapsed_periods']['#suffix'] = "</div>";
	return $form;
}
 
/**
 *  Implements hook_pathauto_entity_alias_settings_alter().
 */
function publication_pathauto_entity_alias_settings_alter(&$entity_forms) {
  $entity_forms += array(
      'publication' => 'publication_form',
  );
}

/*
 * Implements hook_preprocess_entity
 */
function publication_preprocess_entity(&$vars){
	$range = null;
	$elements = $vars['elements'];
	$view_mode = $vars['view_mode'];
	if(isset($elements['field_pub_dataset'])){
		$range = $elements['field_pub_dataset_range']['#items'][0]['safe_value'];
		if(!is_null($range)) $range = explode(';',$range);
		$vars['dataset']['table'] = '';
		$vars['dataset']['chart'] = draw_chart($elements['field_pub_dataset']['#items'][0]['target_id'],$view_mode,$range);
	}
}

/**
  * Implements hook_views_api().
  */
function publication_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'publication'),
  );
}

/*
 * Implements hook_views_pre_render(&$view)
 */
function publication_views_pre_render(&$view){
	if($view->name == 'publications_search' && $view->current_display == 'statistical_reports'){
		// Build breadcrumb
		count($view->args)? $parents  = taxonomy_get_parents_all($view->args[0]) : $parents = array();		
		$breadcrumb = array();
		$breadcrumb[] = l(t('Home'),'<front>');
		//$breadcrumb[] = l(t('Statistical publications'),'statistical_publications');
		foreach(array_reverse($parents) as $parent){
			$breadcrumb[] = l(t($parent->name),drupal_get_path_alias('page/term/' . $parent->tid));
		}
		
		if(count($view->args)) $breadcrumb[] = t('Statistical reports');
		drupal_set_breadcrumb($breadcrumb);
	}
}


/**
 * Implements hook_search_api_alter_callback_info().
 */
function publication_search_api_alter_callback_info() {
  $callbacks['publication_alter_add_period'] = array(
    'name' => t('Period'),
    'description' => t('Get the days between the today and of datasource incidence covered period end date value.'),
    'class' => 'PublicationAlterAddPeriod',
  );
  return $callbacks;
}

/**
 * Implements hook_theme().
 */
function publication_theme($existing, $type, $theme, $path) {

  $module_path = drupal_get_path('module','publication');
  $items = array();

  $items['render_publication_subjects']  = array(
      			'render element' => 'element',
    				);
  
  return $items;
}

/*
 * Get a chart definition ready for rendering 
 *
 * @param
 *	$pub_id : the publication id
 * @param
 *	$view_mode : View mode
 *	@param
 *	$range : period interval to extract from the dataset 
 *	
 * @return
 *	renderable array for the charts module
 *
 */
function draw_chart($pub_id,$view_mode,$range = array()){
	$pub = publication_load($pub_id);
	$wr = entity_metadata_wrapper('publication',$pub);
	$values = $wr->field_dataset_values->value();
	$table = $values['tabledata'];
   $legend = $row = $x_axis = $data = array();
   

   $legend = array_column($table,0);
   unset($legend[0]);
   $legend = array_values($legend);

	foreach($table as &$row){
		unset($row[0]);
		$row = array_values($row);
	}
   	
	// Get range positions
	if(count($range)){
		$offset = -1;
		$length = null;
		foreach($table as &$row){
			if($offset == -1){ // Initial search
				$offset = array_search($range[0],$row);
				if(array_key_exists('1',$range)) $length = (array_search($range[1],$row) - $offset) + 1 ; // !important : for value $to is included
			}
			$row = array_slice($row,$offset,$length);
		}
	}
	// First row is time-serie	
	$x_axis = $table[0];
	// Remove it
	unset($table[0]);
	$data = array_values($table);	
	
	
 	$chart = array(
	 		'#type' => 'chart',
	 		'#chart_type' => $wr->field_dataset_chart_type->value(),
			'#chart_library' => 'google',
	 		//'#title' => ($view_mode == 'full') ? $pub->title : '',
	    	'#legend' => ($view_mode == 'full') ? TRUE : FALSE,
	    	'#legend_title' => ($view_mode == 'full') ? '' : NULL,
	    	'#legend_position' => ($view_mode == 'full') ? 'bottom' : 'none',
	    	'#legend_font_size' => ($view_mode == 'full') ? '' : '0em',
	    	'#data_labels' => ($view_mode == 'full') ? TRUE : FALSE,
	    	'#width' => ($view_mode == 'full') ? '' : '315px',
	    	'#height'=> ($view_mode == 'full') ? '' : '150px',
	);
		
	foreach($legend as $index => $value){
		$chart[$value] = array(
			'#type' => 'chart_data',
			'#title' => $value,
			'#data' => array_map('floatval',$data[$index]),
			'#decimal_count' => 1,
			'#show_in_legend' => ($view_mode == 'full') ? TRUE : FALSE,		
			'#show_labels' => ($view_mode == 'full') ? TRUE : FALSE,
		);	
		//if($wr->field_dataset_chart_data_prefix->value()) $chart[$value]['#prefix'] = $wr->field_dataset_chart_data_prefix->value();
		//if($wr->field_dataset_chart_data_suffix->value()) $chart[$value]['#suffix'] = ' ' . $wr->field_dataset_chart_data_suffix->value();
	}
	
	$chart['xaxis'] = array(
		'#type' => 'chart_xaxis', 
		'#labels' => $x_axis,
	);
	
	$chart['yaxis'] = array(
		'#type' => 'chart_yaxis',
		'#labels' => NULL,
	);

   return $chart;
   	
}

/**
 * Implements hook_theme_registry_alter().
 */
function publication_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'publication');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

/**
 ***************************************************************************************
 * Theme functions
 ***************************************************************************************
 */
/* This #theme function has the responsibility of consolidating/rendering the
 * children's markup and returning it, where it will be placed in the
 * element's #children property.
 */
function theme_render_publication_subjects(&$variables) {
  $output = '';
  foreach (element_children($variables['element']['child']) as $item) {
    //$output .= render($variables['element']['child'][$item]) . $variables['element']['#separator'];
  }
  return $output;
}


/*******************************************************************************
 ********************************* Publication API's **********************************
 ******************************************************************************/

/**
 * Access callback for Publication.
 */
function publication_access($op, $publication = NULL, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }

  switch ($op) {
  	 case 'administrer':
      return user_access('administer publication entities', $account);
    case 'create':
      return user_access('administer publication entities', $account)
          || user_access('create publication entities', $account);
    case 'view':
      return user_access('administer publication entities', $account)
          || user_access('view publication entities', $account);
    case 'insert':
    case 'edit' :
    case 'update' :
    case 'delete':
      return user_access('administer publication entities')
          || user_access('edit any publication entities')
          || (user_access('edit own publication entities') && ($publication->uid == $account->uid));
    default:
		//return TRUE;    
    
  }
}

/**
 * Load a Publication.
 */
function publication_load($pub_id, $reset = FALSE) {
  $publications = publication_load_multiple(array($pub_id), array(), $reset);
  return reset($publications);
}

/**
 * Load multiple Publications based on certain conditions.
 */
function publication_load_multiple($pub_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('publication', $pub_ids, $conditions, $reset);
}

/**
 * Save Publication.
 */
function publication_save($publication) {
  entity_save('publication', $publication);
}

/**
 * Delete single Publication.
 */
function publication_delete($publication) {
  entity_delete('publication', entity_id('publication' ,$publication));
}

/**
 * Delete multiple Publications.
 */
function publication_delete_multiple($publication_ids) {
  entity_delete_multiple('publication', $publication_ids);
}

/*******************************************************************************
 ****************************** Publication Type API's ********************************
 ******************************************************************************/

/**
 * Access callback for Publication Type.
 */
function publication_type_access($op, $entity = NULL) {
  return user_access('administer publication types');
}

/**
 * Load Publication Type.
 */
function publication_type_load($publication_type) {
  return publication_types($publication_type);
}

/**
 * List of Publication Types.
 */
function publication_types($type_name = NULL) {
  $types = entity_load_multiple_by_name('publication_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}

/**
 * Save Publication type entity.
 */
function publication_type_save($publication_type) {
  entity_save('publication_type', $publication_type);
}

/**
 * Delete single case type.
 */
function publication_type_delete($publication_type) {
  entity_delete('publication_type', entity_id('publication_type' ,$publication_type));
}

/**
 * Delete multiple case types.
 */
function publication_type_delete_multiple($publication_type_ids) {
  entity_delete_multiple('publication_type', $publication_type_ids);
}
