<?php

/**
 * @file
 * NISR Message module 
 */

/*
 * Implements hook_application_insert
 *
 * Send Email message notifications on visa creation
 */
function nisr_message_application_insert($application){
	global $user;
	
	// To do : Remove. Make this configurable via UI
	if($application->type == 'visa'){
		$message = message_create('visa_new_application',array('uid' => $user->uid));	
		$msg = entity_metadata_wrapper('message',$message);
	
		$msg->field_message_visa->set($application);
		
		if($application->uid == $user->uid){
			// Send notification to Visa crew
			foreach(get_users_by_role('Visa manager') as $visa_manager){
			$options['mail'] .= $visa_manager->mail . ',' ;
		}	
		
		$options['mail'] = substr($options['mail'], 0, -1);
		
		}else{
			// Send notification to Visa request's author
			$author = user_load($application->uid);
			$options['mail'] = $author->mail;
		}
				
		message_notify_send_message($message,$options);
	}
}

/*
 * Implements hook_publication_insert
 *
 * Send Various Email message notifications
 */
function nisr_message_publication_insert($publication){
	global $user;
	// To do : Remove. Make this condition configurable via UI
	if(in_array($publication->type,array('document','statistical_report'))){
		$pub = entity_metadata_wrapper('publication',$publication);
		$term_id = ($publication->type == 'document') ? $pub->field_doc_subject->tid->value() : $pub->field_pub_subject->tid->value();
		$subject = taxonomy_term_load($term_id);
		
		$message = message_create('publication_new',array('uid' => $user->uid));	
		$msg = entity_metadata_wrapper('message',$message);
	
		$msg->field_message_publication->set($publication);
				
		message_subscribe_send_message('taxonomy_term',$subject,$message);
	}
}

/*
 * Implements hook_form_FORM_ID_alter()
 */
function nisr_message_form_message_type_form_alter(&$form,&$form_state,$form_id){
	$index = 0;
	$loop = TRUE;
	while($loop){
		if(isset($form['message_type_fields']['message_text']['en'][$index])){
			// Disable the wysiwyg editor
			$form['message_type_fields']['message_text']['en'][$index]['#wysiwyg'] = FALSE;
			++$index; 
		}else{
			$loop = FALSE;	
		}
	}
}

