<?php

/**
 * @file
 * Service module suite
 */

/*
 *	Implements hook_menu()
 */
function nisr_service_menu(){
	$items = array();
		
	$items['ServiceLogin'] = array(
		'title' => 'Login',
		'page callback' => 'serviceLogin',
		'access callback' => TRUE,
	);

	$items['ServiceRegister'] = array(
		'title' => 'Register',
		'page callback' => 'serviceRegister',
		'access callback' => TRUE,	
	
	);
		
	$items['service/visa'] = array(
		'title' => 'Visa',
		'page callback' => 'nisr_service_user_is_logged_in',
		'page arguments' => array('visa'),
		'access callback' => TRUE,
    	'type' => MENU_NORMAL_ITEM,
    	'menu_name' => 'menu-services',
    	'weight' => -50,
	);
			
	return $items;	
}


/*
 * Implements hook_preprocess_page()
 */
function nisr_service_preprocess_page(&$variables){
	$path = arg();
	if(in_array($path[0],array('ServiceLogin','ServiceRegister'))){
		$variables['theme_hook_suggestions'][] = 'nisr_service_gateway';
	}
}

/*
 * Implements hook_theme()
 */
function nisr_service_theme($existing, $type, $theme, $path){
	$items['nisr_service_gateway'] = array(
		'render element' => 'page',
		'template' => 'nisr_service_gateway',
		'path' => drupal_get_path('module','nisr_service') . '/theme',
	);
	$items['nisr_service_login_form'] = array(
        'render element' => 'form',
        'template' => 'nisr_service_login',
        'path' => drupal_get_path('module', 'nisr_service') . '/theme',
    );

    $items['nisr_service_register_form'] = array(
        'render element' => 'form',
        'template' => 'nisr_service_register',
        'path' => drupal_get_path('module', 'nisr_service') . '/theme',
    );

    return $items;
	
}

/*
 * Check if user is logged and redirect to custom login page if not 
 *
 * @return 
 *		Boolean
 */
function nisr_service_user_is_logged_in($service){
	if(!user_is_logged_in()){
		drupal_set_message(t('To use any of our services, you need to login first'));
		drupal_goto('ServiceLogin',array('query' => array('destination'=> 'service/' . $service)));
	}else{
		return views_embed_view($service,'embed_1');
	}
}

/*
 * Service login
 */
function serviceLogin(){
	if(!user_is_logged_in()){
		module_load_include('inc','nisr_service','nisr_service.authentication');
		return drupal_get_form('nisr_service_login_form');
	}
}

/*
 * Service Register
 */
function serviceRegister(){
	if(!user_is_logged_in()){
		module_load_include('inc','nisr_service','nisr_service.authentication');
		return drupal_get_form('nisr_service_register_form');
	}	
}
