<?php

/**
 * @file
 * NISR Service module
 */

/*
 *	Implements hook_menu()
 */
function nisr_service_menu(){
	$items = array();
		
	$items['ServiceLogin'] = array(
		'title' => 'Login',
		'page callback' => 'serviceLogin',
		'access callback' => TRUE,
	);

	$items['ServiceRegister'] = array(
		'title' => 'Register',
		'page callback' => 'serviceRegister',
		'access callback' => TRUE,	
	
	);
	
	$items['ServiceRecoverPassword'] = array(
		'title' => 'Request new password',
    	'page callback' => 'serviceRecoverPassword',
		'access callback' => TRUE,	
	);
	
	$items['admin/services'] = array(
		'title' => 'Services management',
    	'type' => MENU_NORMAL_ITEM,
    	'access callback' => 'nisr_service_user_has_role',
    	'access arguments' => array(array('Visa manager','administrator','Internships manager')),
    	'description' => 'Application forms(Visa/Internships) management pool',
    	'menu_name' => 'management',
    	'weight' => -9,
	
	);
	
	$items['service/visa'] = array(
		'title' => 'Visa',
		'page callback' => 'nisr_service_user_is_logged_in',
		'page arguments' => array('visa'),
		'access callback' => TRUE,
    	'type' => MENU_NORMAL_ITEM,
    	'menu_name' => 'menu-services',
    	'weight' => -50,
	);

	$items['service/subscribe/%/%/%'] = array(
		'title' => 'Subscribe',
		'page callback' => 'nisr_service_subscribe',
		'page arguments' => array(2,3,4),
		'access callback' => TRUE,
    	'type' => MENU_CALLBACK,
	);
				
	return $items;	
}

/*
 * Implements hook_menu_alter()
 */
function nisr_service_menu_alter(&$items){
	// Provide top level access to admin menu
	$items['admin']['access callback'] = 'nisr_service_user_has_role';
	$items['admin']['access arguments'] = array(array('Visa manager','Internships manager','administrator'));	
}

/*
 * Implements hook_preprocess_page()
 */
function nisr_service_preprocess_page(&$variables){
	$path = arg();
	if(in_array($path[0],array('ServiceLogin','ServiceRegister','ServiceRecoverPassword'))){
		$variables['theme_hook_suggestions'][] = 'nisr_service_gateway';
	}
}

/*
 * Implements hook_theme()
 */
function nisr_service_theme($existing, $type, $theme, $path){
	$items['nisr_service_gateway'] = array(
		'render element' => 'page',
		'template' => 'nisr_service_gateway',
		'path' => drupal_get_path('module','nisr_service') . '/theme',
	);
	$items['nisr_service_login_form'] = array(
        'render element' => 'form',
        'template' => 'nisr_service_login',
        'path' => drupal_get_path('module', 'nisr_service') . '/theme',
    );

    $items['nisr_service_register_form'] = array(
        'render element' => 'form',
        'template' => 'nisr_service_register',
        'path' => drupal_get_path('module', 'nisr_service') . '/theme',
    );
    
	$items['nisr_service_recover_password_form'] = array(
        'render element' => 'form',
        'template' => 'nisr_service_recover_password',
        'path' => drupal_get_path('module', 'nisr_service') . '/theme',
    );
    return $items;
	
}

/*
 * NISR Service Implementation of user_has_role() 
 *	@param
 *		string array $roles : roles checked against	
 * @return 
 *		Boolean
 */
function nisr_service_user_has_role($roles){
	global $user;
	$access = FALSE;
	
	if($user->uid != 1){
		foreach($roles as $role){
			if(in_array($role,$user->roles)){
				 $access = TRUE ;
				 break;
			}	
		}
	}else{
		// User 1 rules
		$access = TRUE;
	}
	
	return $access;		
}


/*
 * Check if user is logged and redirect to custom login page if not 
 *
 * @return 
 *		Boolean
 */
function nisr_service_user_is_logged_in($service){
	if(!user_is_logged_in()){
		drupal_goto('ServiceLogin',array('query' => array('destination'=> 'service/' . $service)));
	}else{
		$view = views_get_view($service);
		$view->set_display('embed_1');
		$view->pre_execute();
		$view->execute();
		if(!count($view->result) && isset($_GET['action']) && $_GET['action'] == 'apply'){
			drupal_goto('/application/add/' . $service);
		}else{
			return views_embed_view($service,'embed_1');
		}	
	}
}

/*
 * Subscription callback for anonymous user
 * Once logged in, this routine will create the flag and get back to the requesting page
 * 
 */
function nisr_service_subscribe($flag_type,$entity_id,$page){
	
	if(user_is_logged_in()){
		$flag = flag_get_flag($flag_type);
		if(!$flag->is_flagged($entity_id)){
			$flag->flag('flag',$entity_id);
		}
	}
	
	drupal_goto(str_replace('--','/',$page));
}

/*
 * Service login
 */
function serviceLogin(){
	if(!user_is_logged_in()){
		module_load_include('inc','nisr_service','nisr_service.authentication');
		return drupal_get_form('nisr_service_login_form');
	}
}

/*
 * Service Register
 */
function serviceRegister(){
	if(!user_is_logged_in()){
		module_load_include('inc','nisr_service','nisr_service.authentication');
		return drupal_get_form('nisr_service_register_form');
	}	
}

/*
 * Recover password
 */
function serviceRecoverPassword(){
	if(!user_is_logged_in()){
		module_load_include('inc','nisr_service','nisr_service.authentication');
		return drupal_get_form('nisr_service_recover_password_form');
	}	
}
