<?php
/**
 * @file
 * nisr_features.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function nisr_features_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Procurement plan',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04bb4185-5873-47e9-9fe3-e8a08821decf',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Season C',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05acac24-75ce-4b35-856c-2a0f92545889',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/season-c',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Auction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07ce0a9e-3a28-4c07-bd4c-2db77aef188b',
    'vocabulary_machine_name' => 'story_topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Top',
    'description' => 'Ad shown on top ',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ab5c21b-b738-4b6f-8cde-d72d29c0b0ab',
    'vocabulary_machine_name' => 'vocabulary_3',
    'url_alias' => array(
      0 => array(
        'alias' => 'category/ad-groups/top',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Story',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2bce6c5a-cd78-461b-a706-8fe5253d8764',
    'vocabulary_machine_name' => 'story_topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Season A',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e9098ab-8da3-4905-b746-c1abd0a6320d',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/season',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Documentation',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33511fc8-4be0-4a5f-a206-3a7a4fcce8af',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Analyst',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33ad6989-f748-486d-8f30-219cd920402d',
    'vocabulary_machine_name' => 'profile_occupation',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Fiscal year',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '52ea29dc-ff25-4757-91b2-9e1cc8992984',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/fiscal-year',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Annual reports',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5814a811-587a-4822-aa37-1e41dfda3972',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Season B',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5dac3eeb-5e94-4fd3-b4c2-85086ea35524',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/season-b',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Researcher',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75cb847b-8784-46f3-b716-4016b2ef1d54',
    'vocabulary_machine_name' => 'profile_occupation',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'NSDS',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79b88af7-a447-43e7-a22b-960b36f33fec',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Quarter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '865f23e3-4a7c-4d3a-9e34-fdb55b8659a4',
    'vocabulary_machine_name' => 'tags',
    'url_alias' => array(
      0 => array(
        'alias' => 'tags/quarter',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Visa',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90ce100e-ccda-4b0f-a371-b0e587693a8d',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Job',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98af1e1a-4666-439c-920a-5cfd3c2014ba',
    'vocabulary_machine_name' => 'story_topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Standards and Methods',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a213b5c7-dd0b-4dc5-bf0b-c10069d24b0a',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Maps',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af312d4c-2edb-4326-9580-548212350db7',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Right middle',
    'description' => 'Ads to be shown on the middle of the right sidebar',
    'format' => NULL,
    'weight' => 2,
    'uuid' => 'afc0ebf7-3bef-4032-911b-8b752fdf403d',
    'vocabulary_machine_name' => 'vocabulary_3',
    'url_alias' => array(
      0 => array(
        'alias' => 'category/ad-groups/right-middle',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Right bottom',
    'description' => 'Ads on bottom of the right sidebar',
    'format' => NULL,
    'weight' => 3,
    'uuid' => 'c32a9a06-230f-4ef7-954f-46ba7d43e62e',
    'vocabulary_machine_name' => 'vocabulary_3',
    'url_alias' => array(
      0 => array(
        'alias' => 'category/ad-groups/right-bottom',
        'language' => 'und',
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rwanda in figures',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c897224e-d223-4fd2-94d2-2f3b3df0d9c4',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tender',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf663ed3-4492-4e67-a624-74c2d0d905f4',
    'vocabulary_machine_name' => 'story_topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Student',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ecaa1c8f-0c83-4dbd-bb03-2de628050904',
    'vocabulary_machine_name' => 'profile_occupation',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Release calendar',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fca50e77-53c7-4154-b4fd-522bdfe7f6ec',
    'vocabulary_machine_name' => 'document_subjects',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Right top',
    'description' => 'Ads on the top of the right sidebar',
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'fffb5c6d-bb9a-4d30-b1fd-bc4e5b9161c8',
    'vocabulary_machine_name' => 'vocabulary_3',
    'url_alias' => array(
      0 => array(
        'alias' => 'category/ad-groups/right-top',
        'language' => 'und',
      ),
    ),
  );
  return $terms;
}
